name: Bug Report
description: Report a bug in a MAP v1 implementation
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      options:
        - Python (map1)
        - Node.js (@map1/map1)
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Minimal code or JSON input to reproduce
      render: shell
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, runtime version, locale
      placeholder: |
        OS: Ubuntu 24.04
        Python: 3.12.1
        Locale: en_US.UTF-8
