name: Conformance Failure
description: Report a conformance vector mismatch
title: "[Conformance]: "
labels: ["conformance", "critical"]
body:
  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      options:
        - Python (map1)
        - Node.js (@map1/map1)
        - Third-party
    validations:
      required: true
  - type: input
    id: vector_id
    attributes:
      label: Failing Vector ID(s)
      placeholder: "e.g. FULL_001, BIND_003"
    validations:
      required: true
  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Expected vs Actual
      description: Show the expected and actual MID or error code
      render: shell
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, runtime version, locale, endianness
      placeholder: |
        OS: macOS 15.2
        Python: 3.13.0
        Locale: en_US.UTF-8
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any analysis of the root cause
