name: Feature Request
description: Propose a new feature or spec enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Spec (normative change)
        - Spec (non-normative / guidance)
        - Python implementation
        - Node implementation
        - CLI / tooling
        - Conformance suite
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your proposed approach
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      options:
        - label: This would require a new spec version (MID values would change)
